accounts/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('registerUser/',views.registerUser,name='registerUser')
]

foodOnline_main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from .views import home 
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('', include('accounts.urls')),

    # path('marketplace/', include('marketplace.urls')),

    # # CART
    # path('cart/', MarketplaceViews.cart, name='cart'),
    # # SEARCH
    # path('search/', MarketplaceViews.search, name='search'),

    # # CHECKOUT
    # path('checkout/', MarketplaceViews.checkout, name='checkout'),

    # # ORDERS
    # path('orders/', include('orders.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# urls.py

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db.models.fields.related import ForeignKey, OneToOneField

from django.contrib.gis.db import models as gismodels
from django.contrib.gis.geos import Point

# Create your models here.
class UserManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError('User must have an email address')

        if not username:
            raise ValueError('User must have an username')

        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, username, email, password=None):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            password = password,
            first_name = first_name,
            last_name = last_name,
        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    VENDOR = 1
    CUSTOMER = 2

    ROLE_CHOICE = (
        (VENDOR, 'Vendor'),
        (CUSTOMER, 'Customer'),
    )
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=12, blank=True)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICE, blank=True, null=True)

    # required fields
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = UserManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

    def get_role(self):
        if self.role == 1:
            user_role = 'Vendor'
        elif self.role == 2:
            user_role = 'Customer'
        return user_role


class UserProfile(models.Model):
    user = OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    profile_picture = models.ImageField(upload_to='users/profile_pictures', blank=True, null=True)
    cover_photo = models.ImageField(upload_to='users/cover_photos', blank=True, null=True)
    address = models.CharField(max_length=250, blank=True, null=True)
    country = models.CharField(max_length=15, blank=True, null=True)
    state = models.CharField(max_length=15, blank=True, null=True)
    city = models.CharField(max_length=15, blank=True, null=True)
    pin_code = models.CharField(max_length=6, blank=True, null=True)
    latitude = models.CharField(max_length=20, blank=True, null=True)
    longitude = models.CharField(max_length=20, blank=True, null=True)
    location = gismodels.PointField(blank=True, null=True, srid=4326)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    # def full_address(self):
    #     return f'{self.address_line_1}, {self.address_line_2}'

    def __str__(self):
        return self.user.email


    def save(self, *args, **kwargs):
        if self.latitude and self.longitude:
            self.location = Point(float(self.longitude), float(self.latitude))
            return super(UserProfile, self).save(*args, **kwargs)
        return super(UserProfile, self).save(*args, **kwargs)

accounts/forms.py
from django import forms
from .models import User, UserProfile
from .validators import allow_only_images_validator


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError(
                "Password does not match!"
            )


class UserProfileForm(forms.ModelForm):
    address = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Start typing...', 'required': 'required'}))
    profile_picture = forms.FileField(widget=forms.FileInput(attrs={'class': 'btn btn-info'}), validators=[allow_only_images_validator])
    cover_photo = forms.FileField(widget=forms.FileInput(attrs={'class': 'btn btn-info'}), validators=[allow_only_images_validator])
    
    # latitude = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    # longitude = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    class Meta:
        model = UserProfile
        fields = ['profile_picture', 'cover_photo', 'address', 'country', 'state', 'city', 'pin_code', 'latitude', 'longitude']

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if field == 'latitude' or field == 'longitude':
                self.fields[field].widget.attrs['readonly'] = 'readonly'


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'phone_number']

accounts/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.


def registerUser(request):
    return HttpResponse('This test page')

foodOnline_main/views.py
# views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

templates/accounts/custDashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'includes/alerts.html' %}

<!-- Main Section Start -->
<div class="main-section">
    
    {% include 'customers/cover.html' %}
    <div class="page-section account-header buyer-logged-in">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                    <!-- Load the sidebar here -->
                    {% include 'includes/c_sidebar.html' %}
                </div>
                <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                    <div class="user-dashboard loader-holder">
                        <div class="user-holder">
                            <h5 class="text-uppercase">Overview</h5>
                            <div class="row">
                                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                                    <div class="card">
                                        <div class="card-header">
                                            Total Orders
                                        </div>
                                        <div class="card-body text-center">
                                            <a href="#"><h5 class="card-title">{{ orders_count }}</h5></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                                    <div class="card">
                                        <div class="card-header">
                                            Logged in as: <b>{{ user.email }}</b>
                                        </div>
                                        <div class="card-body text-center">
                                            <a href="{% url 'cprofile' %}"><h5 class="card-title"><i class="fa fa-edit"></i> Edit profile</h5></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br>
                            
                            <h5 class="text-uppercase">Recent Orders</h5>
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="user-orders-list">
                                        <div class="responsive-table">
                                            <table class="table table-hover" id="myOrdersTable">
                                                <thead>
                                                  <tr>
                                                    <th scope="col">Order #</th>
                                                    <th scope="col">Name</th>
                                                    <th scope="col">Total</th>
                                                    <th scope="col">Status</th>
                                                    <th scope="col">Date</th>
                                                    <th scope="col">Action</th>
                                                  </tr>
                                                </thead>
                                                <tbody>
                                                    {% for order in recent_orders %}
                                                  <tr>
                                                    <td>{{ order.order_number }}</td>
                                                    <td>{{ order.name }}</td>
                                                    <td>${{ order.total }}</td>
                                                    <td>{{ order.status }}</td>
                                                    <td>{{ order.created_at }}</td>
                                                    <td><a href="" class="btn btn-danger">Details</a></td>
                                                  </tr>
                                                  {% endfor %}
                                                </tbody>
                                              </table>

                                        </div>												
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->


{% endblock %}

templates/accounts/forgot_password.html
{% extends 'base.html' %}

{% block content %}
<!-- Main Section Start -->
<div class="main-section">
    <div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 60px;margin-bottom: 0px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="user-dashboard loader-holder" style="width: 450px; min-height: auto;">
                        <div class="user-holder">
                    <h4 class="text-center" style="margin-bottom: 0;">Forgot your password?</h4>
                    <p class="text-center">Please enter your email address and we will send you a link to reset your password.</p>
                    <hr>
                    <div id="restaurant-sets-holder">
                        <form action="{% url 'forgot_password' %}" class="form-fields-set foodbakery-dev-restaurant-form" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <ul class="register-add-restaurant-tab-container restaurant-information-tab-container">
                                <li>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="row">
                                                
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Email Address</label>
                                                                <input type="email" name="email" placeholder="Enter your email address">
                                                            </div>
                                                        </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="field-holder">
                                                <div class="payment-holder">
                                                    <input type="submit" value="Continue" id="btn-next-restaurant-information" class="bgcolor">
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <!-- Load message -->
                                            {% include 'includes/alerts.html' %}
                                        </div>
                                    </div>

                                </li>
                            </ul>
                        </form>
                    </div>
                </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<!-- Main Section Start -->
<div class="main-section">
    <div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 60px;margin-bottom: 0px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="user-dashboard loader-holder" style="width: 450px; min-height: auto;">
                        <div class="user-holder">
                    <h4 class="text-center" style="margin-bottom: 0;">SIGN IN</h4>
                    <p class="text-center">Order food from your favorite restaurants.</p>
                    <hr>
                    <div id="restaurant-sets-holder">
                        <form action="{% url 'login' %}" class="form-fields-set foodbakery-dev-restaurant-form" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <ul class="register-add-restaurant-tab-container restaurant-information-tab-container">
                                <li>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="row">
                                                
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Email Address</label>
                                                                <input type="email" name="email" placeholder="Enter your email address">
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Password</label>
                                                                <input type="password" name="password" placeholder="Enter your password">
                                                            </div>
                                                        </div>
                                                    
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="field-holder">
                                                <div class="payment-holder">
                                                    <input type="submit" value="Submit" id="btn-next-restaurant-information" class="bgcolor">
                                                    <a href="{% url 'forgot_password' %}" class="float-right">Forgot password</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <!-- Load message -->
                                            {% include 'includes/alerts.html' %}
                                        </div>
                                    </div>

                                </li>
                            </ul>
                        </form>
                    </div>
                </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->
{% endblock %}

templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block content %}
<!-- Main Section Start -->
<div class="main-section">
    <div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 60px;margin-bottom: 0px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="user-dashboard loader-holder" style="width: 450px; min-height: auto;">
                        <div class="user-holder">
                    <h4 class="text-center" style="margin-bottom: 0;">Reset Your Password</h4>
                    
                    <hr>
                    <div id="restaurant-sets-holder">
                        <form action="{% url 'reset_password' %}" class="form-fields-set foodbakery-dev-restaurant-form" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <ul class="register-add-restaurant-tab-container restaurant-information-tab-container">
                                <li>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="row">
                                                
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Password</label>
                                                                <input type="password" name="password" placeholder="Set new password">
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Confirm Password</label>
                                                                <input type="password" name="confirm_password" placeholder="Confirm new password">
                                                            </div>
                                                        </div>
                                                    
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="field-holder">
                                                <div class="payment-holder">
                                                    <input type="submit" value="Reset Password" id="btn-next-restaurant-information" class="bgcolor">
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <!-- Load message -->
                                            {% include 'includes/alerts.html' %}
                                        </div>
                                    </div>

                                </li>
                            </ul>
                        </form>
                    </div>
                </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home | My Django Project{% endblock %}

{% block content %}
<div class="main-section">
    <!-- Home Pages Elements Start -->
    <!-- Main Search Start -->
    <div class="page-section nopadding cs-nomargin main-search-bar"
        style="padding-top: 200px; padding-bottom: 150px; margin-bottom: 0px; background: url() no-repeat center / cover;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="element-title">
                        <h1
                            style="font-size: 40px; color: #505050; text-transform: uppercase; line-height: 50px; margin-bottom: 25px; text-align:center;">
                            We are in the business of food<br>our restaurants do</h1>
                        <p style="font-size: 18px; letter-spacing: 1px; color: #505050; text-align:center;">
                            Ridiculus sociosqu
                            cursus neque cursus curae ante scelerisque vehicula.</p>
                    </div>
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="main-search fancy bg-holder">
                        <form action="" method="GET">
                            <div class="row">
                                <div class="col-lg-4 col-md-4 col-sm-3 col-xs-12">
                                    <div class="field-holder">
                                        <input type="text" name="keyword" placeholder="Restaurant name or food name">
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-4 col-sm-5 col-xs-12">
                                    <div class="field-holder">
                                        <ul>
                                            <li class="select-location">
                                                <div class="foodbakery-locations-fields-group foodbakery-focus-out">
                                                    <span class="foodbakery-search-location-icon"><i
                                                            class="icon-location"></i></span>

                                                    <input type="text" name="address" class="location-field-text filter"
                                                        id="id_address" required placeholder="All Locations">
                                                    <input type="hidden" name="lat" value="" id="id_latitude">
                                                    <input type="hidden" name="lng" value="" id="id_longitude">
                                                </div>

                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                                    <select name="radius" id="radius" style="height: 50px;" required>
                                        <option value="" selected>Choose Radius</option>
                                        <option value="5">5km</option>
                                        <option value="10">10km</option>
                                        <option value="15">15km</option>
                                        <option value="25">25km</option>
                                        <option value="50">50km</option>
                                        <option value="75">75km</option>
                                        <option value="100">100km</option>
                                    </select>
                                </div>
                                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                                    <div class="field-holder">
                                        <input type="submit" value="Search">
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Main Search End -->

    <!-- Top Restaurants Section Start -->
    <div class="page-section nopadding cs-nomargin"
        style="margin-top: 0px;padding-top: 60px;padding-bottom: 0px;margin-bottom: 0px;background: #ffffff;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="element-title align-left">
                        <h2>Top Restaurants</h2>
                        <p>Explore restaurants, bars, and cafés by locality</p>
                    </div>
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"
                    style="padding-right: 0 !important; padding-left: 0 !important;">
                    <div class="company-logo">
                        <ul>
                            <!-- Static content goes here -->
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Top Restaurants Section End -->
    <!-- Choose From Most Popular Listing Start -->
    <div class="page-section nopadding cs-nomargin"
        style="margin-top: 0px;padding-top: 60px;padding-bottom: 50px;margin-bottom: 0px;background: #ffffff;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="element-title align-center">
                        <h2>Choose From Most Popular Restaurants</h2>
                        <p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p>
                    </div>
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="listing fancy">
                        <ul class="row">
                            <!-- Static content goes here -->
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Choose From Most Popular Listing End -->

    <!-- Home Pages Elements End  -->
</div>

{% endblock %}

templates/includes/alerts.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}} show-notification" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
           <strong>{{message}}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/includes/c_sidebar.html
<div class="user-account-nav user-account-sidebar">
    <div class="user-nav-list">
        <ul>
            <li class="{% if '/custDashboard/' == request.path or '/customer/' == request.path %}active{% endif %}"><a href="{% url 'customer' %}"><i class="icon-dashboard3"></i>Dashboard</a></li>
            <li class="{% if '/my_orders/' in request.path or '/order_detail/' in request.path %}active{% endif %}"><a href="{% url 'customer_my_orders' %}"><i class="icon-add_shopping_cart"></i>My Orders</a></li>
            <li class="{% if '/profile/' in request.path %}active{% endif %}"><a href="{% url 'cprofile' %}"><i class="icon-build"></i>Profile Settings</a></li>
            <li><a class="logout-btn" href="{% url 'logout' %}"><i class="icon-log-out"></i>Signout</a></li>
        </ul>
    </div>
</div>